name: Release to Maven Central
on:
  workflow_dispatch:
    inputs:
      versionNumber:
        description: 'Next version number'
      nextSnapshopVersionNumber:
        description: 'Next SNAPSHOT version number'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Java and Maven
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - id: install-secret-key
        name: Install gpg secret key
        run: |
          cat <(echo -e "${{ secrets.GPG_PRIVATE_KEY }}") | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG
#
#
#
#      - name: Maven Release
#        env:
#          OSSRHUSERNAME: ${{ secrets.OSSRHUSERNAME }}
#          OSSRHPASSWORD: ${{ secrets.OSSRHPASSWORD }}
#        run: mvn -DskipTests -Darguments=-DskipTests release:prepare release:perform -Pdeploy
#
#      - name: Release
#          uses: qcastel/github-actions-maven-release@1.12.26
#          env:
#            JAVA_HOME: /usr/lib/jvm/java-11-openjdk/
#          with:
#            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
#            maven-args: "-DskipTests -DskipITs"
#            git-release-bot-name: "release-bot"
#            git-release-bot-email: "release-bot@serenity-bdd.info"
#            gpg-enabled: "true"
#            gpg-key-id: ${{ secrets.GITHUB_GPG_KEY_ID }}
#            gpg-key: ${{ secrets.GITHUB_GPG_KEY }}