name: Release to Maven Central
on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Configure Maven Servers
        uses: s4u/maven-settings-action@v2.8.0
        with:
          servers: '[{"id": "gpg.passphrase", "passphrase": "${{ secrets.SONATYPE_PASSPHRASE }}"},
                   {"id": "sonatype-nexus-snapshots", "username": "${{ secrets.SONATYPE_USERNAME }}", "password": "${{ secrets.SONATYPE_PASSWORD }}"},
                   {"id": "${{ secrets.SONATYPE_SERVER_ID }}", "username": "${{ secrets.SONATYPE_SERVER_USERNAME }}", "password": "${{ secrets.SONATYPE_SERVER_PASSWORD }}"}]'

      - name: Run Maven Release
        run: mvn release:prepare release:perform -Darguments='-Dmaven.test.skip=true' -Pdeploy
