name: Publish package to the Maven Central Repository and GitHub Packages
workflow_dispatch:
  inputs:
    versionNumber:
      description: 'Next version number'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Java and Maven
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Set Version
        run: mvn versions:set -DnewVersion=${{ github.event.inputs.versionNumber }} && mvn versions:commit

      - name: Tag Version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        run: git commit -a -m"Release version ${{ github.event.inputs.versionNumber }}" && git tag v${{ github.event.inputs.versionNumber }} && git push --tags

      - name: Release Build
        run: mvn clean install -Prelease -T4

      - name: Release Maven package
        uses: samuelmeuli/action-maven-publish@v1
        with:
          gpg_private_key: ${{ secrets.gpg_private_key }}
          gpg_passphrase: ${{ secrets.gpg_passphrase }}
          nexus_username: ${{ secrets.nexus_username }}
          nexus_password: ${{ secrets.nexus_password }}

#      - name: Publish to the Maven Central Repository
#        run: mvn --batch-mode deploy
#        env:
#          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
#          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}