name: Smoke Tests (Chrome)

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 # Update to v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2 # Update to v2
        with:
          distribution: 'temurin' # 'temurin' distribution provides OpenJ9 builds of the OpenJDK
          java-version: '17'

      - name: Cache the Maven packages to speed up build
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Snapshot Build

        run: mvn clean install -T4 -DskipTests

      - name: Smoke Tests
        run: cd serenity-smoketests && mvn verify -Denvironment=chrome
